Discount system + update method tweak
WEEKLY-DISCORD-MEETING-by-LIDL/pos-system pull request #29
Opened 2024-12-16 16:15 UTC by AkvileR

- Added discount system for discounts on products and services. Now Admins and Owners can manage discounts, Regular employees can get them.
- Tweaked the calculation of order item to include a discount.
- Currently there is no alert anywhere that a discount has expired, it doesn't get deleted, it just doesn't add expired discounts to the total price of an order item.
- Fixed some update methods to include a null check of request fields.

2024-12-16 16:25 UTC, aWhiteScreen approved these changes
looks alright to me

2024-12-17 12:28 UTC, mantvydasMac requested changes

2024-12-17 12:28 UTC, mantvydasMac commented on src/main/java/wdmsystem/employee/EmployeeService.java
> +    }
Any reason to do this instead of just using a DTOMapper DTO to model method?

2024-12-17 12:28 UTC, mantvydasMac commented on src/main/java/wdmsystem/utility/DTOMapper.java
> +        return new ProductDTO(product.id, product.merchant.id, product.title, (product.category == null ? null : product.category.id), product.price, product.discount.id, (product.tax == null ? null
product.discount.id should probably be (product.discount == null ? null : product.discount.id) just like with the other fields that can be null

2024-12-17 14:28 UTC, AkvileR commented on src/main/java/wdmsystem/employee/EmployeeService.java
> +    }
There was no particular reason why, the update method itself was getting too big so i carried the logic into a separate method. But you are right, maybe having it in the DTO mapper would make the code overall more uniform.

2024-12-17 17:15 UTC, mantvydasMac approved these changes

2024-12-17 17:15 UTC, merged